#!/bin/bash

mkdir -p /data/logs
DATE=`date +%Y-%m-%d:%H:%M:%S`
echo $DATE >> /data/logs/1min.log
echo $MYSQL_HOST >> /data/logs/1min.log
echo $MYSQL_USER >> /data/logs/1min.log
echo $MYSQL_DB >> /data/logs/1min.log
